package lexer;

public enum TokenType {
    EOF, UN_TAL, A_MUERTE, FIJATE_SI, YSINO, SEGUN_VEA, LA_FAENA, SUELTA, DI,
    NA_DE_NA, PAVOS, APACHAS, CARRO, JURA, JURAO, BULO, IDENTIFIER, INT_LITERAL,
    FLOAT_LITERAL, STRING_LITERAL, LPAREN, RPAREN, LBRACE, RBRACE, SEMICOLON,
    COMMA, ASSIGN, PLUS, MINUS, STAR, SLASH, OR, AND, EQUAL_EQUAL, LESS, GREATER,
    LESS_EQUAL
}
